/**
 * Datos de ejemplo — se usan SOLO si SITE_CONFIG.sheetCsvUrl está vacío,
 * para poder ver el sitio funcionando antes de conectar la planilla real.
 */
window.DEMO_COMERCIOS = [
  {
    nombre: "Almacén Doña Rosa",
    barrio: "Rafael Calzada",
    rubro: "Almacén / Autoservicio",
    whatsapp: "011 15-2233-4455",
    sitioWeb: "https://instagram.com/almacendonarosa",
    direccion: "Av. Calzada 1234, Rafael Calzada",
    imagen: "",
  },
  {
    nombre: "Verdulería El Sol",
    barrio: "Rafael Calzada",
    rubro: "Verdulería y Frutería",
    whatsapp: "11 4213-5566",
    sitioWeb: "",
    direccion: "Belgrano 456, Rafael Calzada",
    imagen: "",
  },
  {
    nombre: "Panadería La Espiga",
    barrio: "Rafael Calzada",
    rubro: "Panadería y Pastelería",
    whatsapp: "011 15-6677-8899",
    sitioWeb: "https://facebook.com/panaderialaespiga",
    direccion: "San Martín 789, Rafael Calzada",
    imagen: "",
  },
  {
    nombre: "Peluquería Estilo Propio",
    barrio: "Rafael Calzada",
    rubro: "Peluquería y Estética",
    whatsapp: "011 15-1122-3344",
    sitioWeb: "",
    direccion: "",
    imagen: "",
  },
  {
    nombre: "Ferretería Central",
    barrio: "Rafael Calzada",
    rubro: "Ferretería y Bazar",
    whatsapp: "11 4213-9900",
    sitioWeb: "https://ferreteriacentralcalzada.com.ar",
    direccion: "Mitre 321, Rafael Calzada",
    imagen: "",
  },
  {
    nombre: "Estudio Contable Pérez",
    barrio: "Rafael Calzada",
    rubro: "Servicios profesionales",
    whatsapp: "011 15-4455-6677",
    sitioWeb: "",
    direccion: "",
    imagen: "",
  },
];
